live_config_reload = true
working_directory = "None"

[window]
dynamic_padding = false
startup_mode = "Windowed"
title = "Alacritty"
class = "Alacritty"

  [window.dimensions]
  columns = 0
  lines = 0

  [window.padding]
  x = 0
  y = 0

[scrolling]
history = 10_000
multiplier = 3

[font]
size = 11

  [font.normal]
  family = "FiraCode Nerd Font"
  style = "Regular"

  [font.bold]
  family = "FiraCode Nerd Font"
  style = "Bold"

  [font.italic]
  family = "JetBrainsMono Nerd Font"
  style = "Italic"

  [font.offset]
  x = 0
  y = 1

  [font.glyph_offset]
  x = 1
  y = 1


[bell]
animation = "EaseOutExpo"
duration = 0
color = "0xffffff"

[[mouse.bindings]]
mouse = "Middle"
action = "Paste"

[mouse]
hide_when_typing = true

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
save_to_clipboard = false

[cursor]
style = "Underline"
unfocused_hollow = true

[debug]
render_timer = false
persistent_logging = false
log_level = "Warn"
print_events = false

[[keyboard.bindings]]
key = "Insert"
mods = "Shift"
action = "Paste"

[[keyboard.bindings]]
key = "Equals"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "L"
mods = "Control"
action = "ClearLogNotice"

[[keyboard.bindings]]
key = "L"
mods = "Control"
chars = "\f"

[[keyboard.bindings]]
key = "Home"
mods = "Alt"
chars = "\u001b[1;3H"

[[keyboard.bindings]]
key = "Home"
chars = "\u001bOH"
mode = "AppCursor"

[[keyboard.bindings]]
key = "Home"
chars = "\u001b[H"
mode = "~AppCursor"

[[keyboard.bindings]]
key = "End"
mods = "Alt"
chars = "\u001b[1;3F"

[[keyboard.bindings]]
key = "End"
chars = "\u001bOF"
mode = "AppCursor"

[[keyboard.bindings]]
key = "End"
chars = "\u001b[F"
mode = "~AppCursor"

[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
action = "ScrollPageUp"
mode = "~Alt"

[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
chars = "\u001b[5;2~"
mode = "Alt"

[[keyboard.bindings]]
key = "PageUp"
mods = "Control"
chars = "\u001b[5;5~"

[[keyboard.bindings]]
key = "PageUp"
mods = "Alt"
chars = "\u001b[5;3~"

[[keyboard.bindings]]
key = "PageUp"
chars = "\u001b[5~"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
action = "ScrollPageDown"
mode = "~Alt"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
chars = "\u001b[6;2~"
mode = "Alt"

[[keyboard.bindings]]
key = "PageDown"
mods = "Control"
chars = "\u001b[6;5~"

[[keyboard.bindings]]
key = "PageDown"
mods = "Alt"
chars = "\u001b[6;3~"

[[keyboard.bindings]]
key = "PageDown"
chars = "\u001b[6~"

[[keyboard.bindings]]
key = "Tab"
mods = "Shift"
chars = "\u001b[Z"

[[keyboard.bindings]]
key = "Back"
chars = "\u007f"

[[keyboard.bindings]]
key = "Insert"
chars = "\u001b[2~"

[[keyboard.bindings]]
key = "Delete"
chars = "\u001b[3~"

[[keyboard.bindings]]
key = "Left"
mods = "Shift"
chars = "\u001b[1;2D"

[[keyboard.bindings]]
key = "Left"
mods = "Control"
chars = "\u001b[1;5D"

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001b[1;3D"

[[keyboard.bindings]]
key = "Left"
chars = "\u001b[D"
mode = "~AppCursor"

[[keyboard.bindings]]
key = "Left"
chars = "\u001bOD"
mode = "AppCursor"

[[keyboard.bindings]]
key = "Right"
mods = "Shift"
chars = "\u001b[1;2C"

[[keyboard.bindings]]
key = "Right"
mods = "Control"
chars = "\u001b[1;5C"

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001b[1;3C"

[[keyboard.bindings]]
key = "Right"
chars = "\u001b[C"
mode = "~AppCursor"

[[keyboard.bindings]]
key = "Right"
chars = "\u001bOC"
mode = "AppCursor"

[[keyboard.bindings]]
key = "Up"
mods = "Shift"
chars = "\u001b[1;2A"

[[keyboard.bindings]]
key = "Up"
mods = "Control"
chars = "\u001b[1;5A"

[[keyboard.bindings]]
key = "Up"
mods = "Alt"
chars = "\u001b[1;3A"

[[keyboard.bindings]]
key = "Up"
chars = "\u001b[A"
mode = "~AppCursor"

[[keyboard.bindings]]
key = "Up"
chars = "\u001bOA"
mode = "AppCursor"

[[keyboard.bindings]]
key = "Down"
mods = "Shift"
chars = "\u001b[1;2B"

[[keyboard.bindings]]
key = "Down"
mods = "Control"
chars = "\u001b[1;5B"

[[keyboard.bindings]]
key = "Down"
mods = "Alt"
chars = "\u001b[1;3B"

[[keyboard.bindings]]
key = "Down"
chars = "\u001b[B"
mode = "~AppCursor"

[[keyboard.bindings]]
key = "Down"
chars = "\u001bOB"
mode = "AppCursor"

[[keyboard.bindings]]
key = "F1"
chars = "\u001bOP"

[[keyboard.bindings]]
key = "F2"
chars = "\u001bOQ"

[[keyboard.bindings]]
key = "F3"
chars = "\u001bOR"

[[keyboard.bindings]]
key = "F4"
chars = "\u001bOS"

[[keyboard.bindings]]
key = "F5"
chars = "\u001b[15~"

[[keyboard.bindings]]
key = "F6"
chars = "\u001b[17~"

[[keyboard.bindings]]
key = "F7"
chars = "\u001b[18~"

[[keyboard.bindings]]
key = "F8"
chars = "\u001b[19~"

[[keyboard.bindings]]
key = "F9"
chars = "\u001b[20~"

[[keyboard.bindings]]
key = "F10"
chars = "\u001b[21~"

[[keyboard.bindings]]
key = "F11"
chars = "\u001b[23~"

[[keyboard.bindings]]
key = "F12"
chars = "\u001b[24~"

[[keyboard.bindings]]
key = "F1"
mods = "Shift"
chars = "\u001b[1;2P"

[[keyboard.bindings]]
key = "F2"
mods = "Shift"
chars = "\u001b[1;2Q"

[[keyboard.bindings]]
key = "F3"
mods = "Shift"
chars = "\u001b[1;2R"

[[keyboard.bindings]]
key = "F4"
mods = "Shift"
chars = "\u001b[1;2S"

[[keyboard.bindings]]
key = "F5"
mods = "Shift"
chars = "\u001b[15;2~"

[[keyboard.bindings]]
key = "F6"
mods = "Shift"
chars = "\u001b[17;2~"

[[keyboard.bindings]]
key = "F7"
mods = "Shift"
chars = "\u001b[18;2~"

[[keyboard.bindings]]
key = "F8"
mods = "Shift"
chars = "\u001b[19;2~"

[[keyboard.bindings]]
key = "F9"
mods = "Shift"
chars = "\u001b[20;2~"

[[keyboard.bindings]]
key = "F10"
mods = "Shift"
chars = "\u001b[21;2~"

[[keyboard.bindings]]
key = "F11"
mods = "Shift"
chars = "\u001b[23;2~"

[[keyboard.bindings]]
key = "F12"
mods = "Shift"
chars = "\u001b[24;2~"

[[keyboard.bindings]]
key = "F1"
mods = "Control"
chars = "\u001b[1;5P"

[[keyboard.bindings]]
key = "F2"
mods = "Control"
chars = "\u001b[1;5Q"

[[keyboard.bindings]]
key = "F3"
mods = "Control"
chars = "\u001b[1;5R"

[[keyboard.bindings]]
key = "F4"
mods = "Control"
chars = "\u001b[1;5S"

[[keyboard.bindings]]
key = "F5"
mods = "Control"
chars = "\u001b[15;5~"

[[keyboard.bindings]]
key = "F6"
mods = "Control"
chars = "\u001b[17;5~"

[[keyboard.bindings]]
key = "F7"
mods = "Control"
chars = "\u001b[18;5~"

[[keyboard.bindings]]
key = "F8"
mods = "Control"
chars = "\u001b[19;5~"

[[keyboard.bindings]]
key = "F9"
mods = "Control"
chars = "\u001b[20;5~"

[[keyboard.bindings]]
key = "F10"
mods = "Control"
chars = "\u001b[21;5~"

[[keyboard.bindings]]
key = "F11"
mods = "Control"
chars = "\u001b[23;5~"

[[keyboard.bindings]]
key = "F12"
mods = "Control"
chars = "\u001b[24;5~"

[[keyboard.bindings]]
key = "F1"
mods = "Alt"
chars = "\u001b[1;6P"

[[keyboard.bindings]]
key = "F2"
mods = "Alt"
chars = "\u001b[1;6Q"

[[keyboard.bindings]]
key = "F3"
mods = "Alt"
chars = "\u001b[1;6R"

[[keyboard.bindings]]
key = "F4"
mods = "Alt"
chars = "\u001b[1;6S"

[[keyboard.bindings]]
key = "F5"
mods = "Alt"
chars = "\u001b[15;6~"

[[keyboard.bindings]]
key = "F6"
mods = "Alt"
chars = "\u001b[17;6~"

[[keyboard.bindings]]
key = "F7"
mods = "Alt"
chars = "\u001b[18;6~"

[[keyboard.bindings]]
key = "F8"
mods = "Alt"
chars = "\u001b[19;6~"

[[keyboard.bindings]]
key = "F9"
mods = "Alt"
chars = "\u001b[20;6~"

[[keyboard.bindings]]
key = "F10"
mods = "Alt"
chars = "\u001b[21;6~"

[[keyboard.bindings]]
key = "F11"
mods = "Alt"
chars = "\u001b[23;6~"

[[keyboard.bindings]]
key = "F12"
mods = "Alt"
chars = "\u001b[24;6~"

[[keyboard.bindings]]
key = "F1"
mods = "Super"
chars = "\u001b[1;3P"

[[keyboard.bindings]]
key = "F2"
mods = "Super"
chars = "\u001b[1;3Q"

[[keyboard.bindings]]
key = "F3"
mods = "Super"
chars = "\u001b[1;3R"

[[keyboard.bindings]]
key = "F4"
mods = "Super"
chars = "\u001b[1;3S"

[[keyboard.bindings]]
key = "F5"
mods = "Super"
chars = "\u001b[15;3~"

[[keyboard.bindings]]
key = "F6"
mods = "Super"
chars = "\u001b[17;3~"

[[keyboard.bindings]]
key = "F7"
mods = "Super"
chars = "\u001b[18;3~"

[[keyboard.bindings]]
key = "F8"
mods = "Super"
chars = "\u001b[19;3~"

[[keyboard.bindings]]
key = "F9"
mods = "Super"
chars = "\u001b[20;3~"

[[keyboard.bindings]]
key = "F10"
mods = "Super"
chars = "\u001b[21;3~"

[[keyboard.bindings]]
key = "F11"
mods = "Super"
chars = "\u001b[23;3~"

[[keyboard.bindings]]
key = "F12"
mods = "Super"
chars = "\u001b[24;3~"

[[keyboard.bindings]]
key = "NumpadEnter"
chars = """

"""
